### ISSUE TITLE
Vivo & FlashX Links

### ISSUE THREAD

**Issue by angomania** [BuXXe/movian-bs-plugin#2]
It´s not an issue but a request.
Could you make the bs-plugin working with Vivo and FlashX stream links?
Most of the series links are dead, only Vivo and FlashX are online.

**Comment by BuXXe** [comment]
I did  not update / use my plugins in some weeks but I already noticed that many host resolvers are making problems. So I really need to update all hoster resolutions (for all my plugins). I dont have much time right now but will work on it as soon as i can.

**Comment by BuXXe** [comment]
Today I outsourced the hoster resolution in a stand alone library. I got vivo working again but as far as I can tell, flashx will not be supported due to the big problems regarding scripted access (the hoster tries to protect the streams from any media player access). I will take a look at the other hosters shortly and release a new plugin version shortly.
